import {
  Scene,
  PerspectiveCamera,
  WebGLRenderer,
  Group,
  Mesh,
  Object3D,
  RingGeometry,
  PlaneGeometry,
  GridHelper,
  CircleGeometry,
  SphereGeometry,
  MeshBasicMaterial,
  ShadowMaterial,
  CanvasTexture,
  HemisphereLight,
  DirectionalLight,
  LightProbe,
  SphericalHarmonics3,
  Color,
  Vector2,
  Vector3,
  Quaternion,
  Matrix4,
  Euler,
  Box3,
  Plane,
  Raycaster,
  SRGBColorSpace,
  ACESFilmicToneMapping,
  EquirectangularReflectionMapping,
  DoubleSide,
  MathUtils,
  PMREMGenerator,
  PCFSoftShadowMap,
} from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import { DRACOLoader } from "three/examples/jsm/loaders/DRACOLoader.js";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";
import { RGBELoader } from "three/examples/jsm/loaders/RGBELoader.js";

export const THREE = {
  Scene,
  PerspectiveCamera,
  WebGLRenderer,
  Group,
  Mesh,
  Object3D,
  RingGeometry,
  PlaneGeometry,
  GridHelper,
  CircleGeometry,
  SphereGeometry,
  MeshBasicMaterial,
  ShadowMaterial,
  CanvasTexture,
  HemisphereLight,
  DirectionalLight,
  LightProbe,
  SphericalHarmonics3,
  Color,
  Vector2,
  Vector3,
  Quaternion,
  Matrix4,
  Euler,
  Box3,
  Plane,
  Raycaster,
  SRGBColorSpace,
  ACESFilmicToneMapping,
  EquirectangularReflectionMapping,
  DoubleSide,
  MathUtils,
  PMREMGenerator,
  PCFSoftShadowMap,
  OrbitControls,
  DRACOLoader,
  GLTFLoader,
  RGBELoader,
};
